#######################################################################################
# A default configuration that will be loaded for all jupyter books
# See the documentation for help and more options: 
# https://jupyterbook.org/customize/config.html

#######################################################################################
# Book settings
title                       : Enterprise FOSS-GIS  # The title of the book. Will be placed in the left navbar.
author                      : Dany Laksono  # The author of the book
copyright                   : "2020"  # Copyright year to be placed in the footer
logo                        : logo.png  # A path to the book logo


# html settings
html:
  favicon             : favicon.ico
  home_page_in_navbar : false
  use_repository_button: true
  use_issues_button : true
  use_edit_page_button: true
  baseurl             : https://www.danylaksono.com/panduan-fossgis/
  extra_navbar        : Buku ini disusun dengan <a href="https://jupyterbook.org">Jupyter Book</a>
  

repository:
  url: https://github.com/danylaksono/panduan-fossgis/
  path_to_book: ./fossgis_enterprise  # An optional path to your book, defaults to repo root
  branch: master  # An optional branch, defaults to `master`
  


latex:
  latex_engine: xelatex
  latex_documents:
     targetname: Enterprise-FOSSGIS.tex

#sphinx:
  #config:
    #latex_toplevel_sectioning: 'part'